language: python

install:
    - pip install flake8 fabric pytz Flask-Testing
    - sudo add-apt-repository -y ppa:chris-lea/node.js
    - sudo apt-get update -qq
    - sudo apt-get install nodejs build-essential dpkg-dev

before_script:
    - cp lwp.example.conf lwp.conf
    - sudo mkdir -p /var/lwp
    - sudo cp lwp.db /var/lwp
    - export PATH=$PATH:$TRAVIS_BUILD_DIR/tests/mock-lxc

script:
    - flake8 --ignore=E501,E402 lwp/ bin/lwp
    - fab build_assets
    - ./setup.py develop
    - python tests/webif.py && python tests/mock_lxc.py
